version: "3"

dotenv:
  - .env

tasks:
  setup:
    desc: Enable builds
    cmds:
      - flutter config --enable-linux-desktop --enable-web

  generate-mocks:
    desc: Generate mocks
    cmds:
      - dart run build_runner build

  .tag-coverage-report:
    internal: true
    silent: true
    requires:
      vars: [tag]
    cmds:
      - genhtml coverage/lcov.{{ .tag }}.info -o coverage/html
      - echo "Coverage report generated at coverage/html/index.html"

  .tag-test:
    internal: true
    silent: true
    requires:
      vars: [tag]
    cmds:
      - flutter test --tags {{ .tag }} --branch-coverage --coverage-path coverage/lcov.{{ .tag }}.info
      - task: .tag-coverage-report
        vars:
          tag: "{{ .tag }}"

  test:unit:
    desc: Run only unit tests
    cmds:
      - task: .tag-test
        vars: { tag: unit }

  test:widget:
    desc: Run only widget tests
    cmds:
      - task: .tag-test
        vars: { tag: widget }

  test:integration:
    desc: Run only integration tests
    cmds:
      - flutter test --tags integration --exclude-tags e2e --branch-coverage --coverage-path coverage/lcov.integration.info
      - task: .tag-coverage-report
        vars: { tag: integration }

  test:e2e:web:
    preconditions:
      - npx @puppeteer/browsers install chromedriver@stable
    desc: Run e2e tests on web
    cmds:
      - chromedriver --port=4444 &
      - flutter drive
        --driver=integration_test/driver.dart
        --target=integration_test/app_test.dart
        -d web

  test:e2e:linux:
    desc: Run e2e tests on Linux
    cmds:
      - flutter drive
        --driver=test/02_integration/driver.dart
        --target=test/02_integration/server_list_e2e_test.dart
        -d linux

  test:all:
    desc: Run all tests
    cmds:
      - task: test:unit
      - task: test:widget
      - task: test:integration
      - genhtml $(ls $(find . -name 'lcov.*.info')) -o coverage/html
      - echo "Coverage report generated at coverage/html/index.html"

  lint:
    desc: Run linter
    cmds:
      - flutter analyze

  format:
    desc: Format code
    cmds:
      - dart format .
  build:web:
    desc: Build for web
    cmds:
      - flutter build web --wasm

  build:linux:
    desc: Build debug linux executable
    deps:
      - setup
    cmds:
      - flutter build linux --release --target-sysroot ./bin/linux

  run:linux:
    desc: Build debug linux executable
    cmds:
      - flutter run -d linux

  run:web:
    desc: Run on web
    cmds:
      - flutter run -d chrome
