// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/00_unit/connection_domain_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cookie_jar/cookie_jar.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:silo_tavern/common/result.dart' as _i4;
import 'package:silo_tavern/domain/connection/repository.dart' as _i2;
import 'package:silo_tavern/services/connection/models/models.dart' as _i8;
import 'package:silo_tavern/services/connection/network.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConnectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionRepository extends _i1.Mock
    implements _i2.ConnectionRepository {
  @override
  _i3.Future<_i4.Result<void>> saveSessionCookies(
    String? serverId,
    List<_i5.Cookie>? cookies,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSessionCookies, [serverId, cookies]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveSessionCookies, [serverId, cookies]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveSessionCookies, [serverId, cookies]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Cookie>?>> loadSessionCookies(
    String? serverId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadSessionCookies, [serverId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Cookie>?>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Cookie>?>>(
                this,
                Invocation.method(#loadSessionCookies, [serverId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i5.Cookie>?>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.Cookie>?>>(
                    this,
                    Invocation.method(#loadSessionCookies, [serverId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.Cookie>?>>);

  @override
  _i3.Future<_i4.Result<void>> saveCsrfToken(String? serverId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveCsrfToken, [serverId, token]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveCsrfToken, [serverId, token]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveCsrfToken, [serverId, token]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<String?>> loadCsrfToken(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#loadCsrfToken, [serverId]),
            returnValue: _i3.Future<_i4.Result<String?>>.value(
              _i6.dummyValue<_i4.Result<String?>>(
                this,
                Invocation.method(#loadCsrfToken, [serverId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<String?>>.value(
              _i6.dummyValue<_i4.Result<String?>>(
                this,
                Invocation.method(#loadCsrfToken, [serverId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<void>> deleteCsrfToken(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCsrfToken, [serverId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteCsrfToken, [serverId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteCsrfToken, [serverId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [ConnectionSessionInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionSessionInterface extends _i1.Mock
    implements _i7.ConnectionSessionInterface {
  @override
  _i3.Future<void> obtainCsrfToken() =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> authenticate(_i8.ConnectionCredentials? credentials) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [credentials]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkServerAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i5.Cookie>> getSessionCookies() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionCookies, []),
            returnValue: _i3.Future<List<_i5.Cookie>>.value(<_i5.Cookie>[]),
            returnValueForMissingStub: _i3.Future<List<_i5.Cookie>>.value(
              <_i5.Cookie>[],
            ),
          )
          as _i3.Future<List<_i5.Cookie>>);

  @override
  void setCsrfToken(String? token) => super.noSuchMethod(
    Invocation.method(#setCsrfToken, [token]),
    returnValueForMissingStub: null,
  );
}
