// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/00_unit/connection_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientRequest_1 extends _i1.SmartFake
    implements _i2.HttpClientRequest {
  _FakeHttpClientRequest_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_2 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_3 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_4 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_5 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_6 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_7 extends _i1.SmartFake implements _i3.AppleOptions {
  _FakeAppleOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  @override
  Duration get idleTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#idleTimeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#idleTimeout)),
            returnValueForMissingStub: _FakeDuration_0(
              this,
              Invocation.getter(#idleTimeout),
            ),
          )
          as Duration);

  @override
  bool get autoUncompress =>
      (super.noSuchMethod(
            Invocation.getter(#autoUncompress),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set idleTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#idleTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set connectionTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#connectionTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxConnectionsPerHost(int? value) => super.noSuchMethod(
    Invocation.setter(#maxConnectionsPerHost, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoUncompress(bool? value) => super.noSuchMethod(
    Invocation.setter(#autoUncompress, value),
    returnValueForMissingStub: null,
  );

  @override
  set userAgent(String? value) => super.noSuchMethod(
    Invocation.setter(#userAgent, value),
    returnValueForMissingStub: null,
  );

  @override
  set authenticate(_i4.Future<bool> Function(Uri, String, String?)? f) =>
      super.noSuchMethod(
        Invocation.setter(#authenticate, f),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
    _i4.Future<_i2.ConnectionTask<_i2.Socket>> Function(Uri, String?, int?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#connectionFactory, f),
    returnValueForMissingStub: null,
  );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
    Invocation.setter(#findProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set authenticateProxy(
    _i4.Future<bool> Function(String, int, String, String?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#authenticateProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set badCertificateCallback(
    bool Function(_i2.X509Certificate, String, int)? callback,
  ) => super.noSuchMethod(
    Invocation.setter(#badCertificateCallback, callback),
    returnValueForMissingStub: null,
  );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.setter(#keyLog, callback),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#open, [method, host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> openUrl(String? method, Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#openUrl, [method, url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#get, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> getUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#getUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#getUrl, [url])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#getUrl, [url])),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> postUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#postUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> putUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#putUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#putUrl, [url])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#putUrl, [url])),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> deleteUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> patchUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#patchUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#head, [host, port, path]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  _i4.Future<_i2.HttpClientRequest> headUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#headUrl, [url]),
            returnValue: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addCredentials, [url, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addProxyCredentials, [host, port, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  @override
  _i3.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_2(this, Invocation.getter(#iOptions)),
            returnValueForMissingStub: _FakeIOSOptions_2(
              this,
              Invocation.getter(#iOptions),
            ),
          )
          as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_3(
              this,
              Invocation.getter(#aOptions),
            ),
            returnValueForMissingStub: _FakeAndroidOptions_3(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_4(
              this,
              Invocation.getter(#lOptions),
            ),
            returnValueForMissingStub: _FakeLinuxOptions_4(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_5(
              this,
              Invocation.getter(#wOptions),
            ),
            returnValueForMissingStub: _FakeWindowsOptions_5(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_6(
              this,
              Invocation.getter(#webOptions),
            ),
            returnValueForMissingStub: _FakeWebOptions_6(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i3.WebOptions);

  @override
  _i3.AppleOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeAppleOptions_7(
              this,
              Invocation.getter(#mOptions),
            ),
            returnValueForMissingStub: _FakeAppleOptions_7(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i3.AppleOptions);

  @override
  Map<String, List<_i5.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
            Invocation.getter(#getListeners),
            returnValue: <String, List<_i5.ValueChanged<String?>>>{},
            returnValueForMissingStub:
                <String, List<_i5.ValueChanged<String?>>>{},
          )
          as Map<String, List<_i5.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i5.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i5.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> write({
    required String? key,
    required String? value,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> read({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> containsKey({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> delete({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>> readAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> deleteAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i4.Future<bool?>.value(),
            returnValueForMissingStub: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);
}
