// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/00_unit/debug_logger_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dio/src/cancel_token.dart' as _i7;
import 'package:dio/src/dio_exception.dart' as _i4;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/headers.dart' as _i3;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/redirect_record.dart' as _i9;
import 'package:dio/src/response.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestOptions_1 extends _i1.SmartFake
    implements _i2.RequestOptions {
  _FakeRequestOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHeaders_2 extends _i1.SmartFake implements _i3.Headers {
  _FakeHeaders_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStackTrace_3 extends _i1.SmartFake implements StackTrace {
  _FakeStackTrace_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDioException_4 extends _i1.SmartFake implements _i4.DioException {
  _FakeDioException_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptorState_5<T> extends _i1.SmartFake
    implements _i5.InterceptorState<T> {
  _FakeInterceptorState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RequestOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestOptions extends _i1.Mock implements _i2.RequestOptions {
  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_0(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_0(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  set sourceStackTrace(StackTrace? value) => super.noSuchMethod(
    Invocation.setter(#sourceStackTrace, value),
    returnValueForMissingStub: null,
  );

  @override
  set data(dynamic value) => super.noSuchMethod(
    Invocation.setter(#data, value),
    returnValueForMissingStub: null,
  );

  @override
  set path(String? value) => super.noSuchMethod(
    Invocation.setter(#path, value),
    returnValueForMissingStub: null,
  );

  @override
  set cancelToken(_i7.CancelToken? value) => super.noSuchMethod(
    Invocation.setter(#cancelToken, value),
    returnValueForMissingStub: null,
  );

  @override
  set onReceiveProgress(_i2.ProgressCallback? value) => super.noSuchMethod(
    Invocation.setter(#onReceiveProgress, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendProgress(_i2.ProgressCallback? value) => super.noSuchMethod(
    Invocation.setter(#onSendProgress, value),
    returnValueForMissingStub: null,
  );

  @override
  String get method =>
      (super.noSuchMethod(
            Invocation.getter(#method),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#method),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#method),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get preserveHeaderCase =>
      (super.noSuchMethod(
            Invocation.getter(#preserveHeaderCase),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ResponseType get responseType =>
      (super.noSuchMethod(
            Invocation.getter(#responseType),
            returnValue: _i2.ResponseType.json,
            returnValueForMissingStub: _i2.ResponseType.json,
          )
          as _i2.ResponseType);

  @override
  _i2.ValidateStatus get validateStatus =>
      (super.noSuchMethod(
            Invocation.getter(#validateStatus),
            returnValue: (int? status) => false,
            returnValueForMissingStub: (int? status) => false,
          )
          as _i2.ValidateStatus);

  @override
  bool get receiveDataWhenStatusError =>
      (super.noSuchMethod(
            Invocation.getter(#receiveDataWhenStatusError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Map<String, dynamic> get extra =>
      (super.noSuchMethod(
            Invocation.getter(#extra),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get followRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#followRedirects),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get maxRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#maxRedirects),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ListFormat get listFormat =>
      (super.noSuchMethod(
            Invocation.getter(#listFormat),
            returnValue: _i2.ListFormat.csv,
            returnValueForMissingStub: _i2.ListFormat.csv,
          )
          as _i2.ListFormat);

  @override
  set method(String? value) => super.noSuchMethod(
    Invocation.setter(#method, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, dynamic>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  set preserveHeaderCase(bool? value) => super.noSuchMethod(
    Invocation.setter(#preserveHeaderCase, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#sendTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set receiveTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#receiveTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentType(String? contentType) => super.noSuchMethod(
    Invocation.setter(#contentType, contentType),
    returnValueForMissingStub: null,
  );

  @override
  set responseType(_i2.ResponseType? value) => super.noSuchMethod(
    Invocation.setter(#responseType, value),
    returnValueForMissingStub: null,
  );

  @override
  set validateStatus(_i2.ValidateStatus? value) => super.noSuchMethod(
    Invocation.setter(#validateStatus, value),
    returnValueForMissingStub: null,
  );

  @override
  set receiveDataWhenStatusError(bool? value) => super.noSuchMethod(
    Invocation.setter(#receiveDataWhenStatusError, value),
    returnValueForMissingStub: null,
  );

  @override
  set extra(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#extra, value),
    returnValueForMissingStub: null,
  );

  @override
  set followRedirects(bool? value) => super.noSuchMethod(
    Invocation.setter(#followRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxRedirects(int? value) => super.noSuchMethod(
    Invocation.setter(#maxRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set persistentConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#persistentConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set requestEncoder(_i2.RequestEncoder? value) => super.noSuchMethod(
    Invocation.setter(#requestEncoder, value),
    returnValueForMissingStub: null,
  );

  @override
  set responseDecoder(_i2.ResponseDecoder? value) => super.noSuchMethod(
    Invocation.setter(#responseDecoder, value),
    returnValueForMissingStub: null,
  );

  @override
  set listFormat(_i2.ListFormat? value) => super.noSuchMethod(
    Invocation.setter(#listFormat, value),
    returnValueForMissingStub: null,
  );

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get queryParameters =>
      (super.noSuchMethod(
            Invocation.getter(#queryParameters),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set queryParameters(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#queryParameters, value),
    returnValueForMissingStub: null,
  );

  @override
  set connectTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#connectTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.RequestOptions copyWith({
    String? method,
    Duration? sendTimeout,
    Duration? receiveTimeout,
    Duration? connectTimeout,
    dynamic data,
    String? path,
    Map<String, dynamic>? queryParameters,
    String? baseUrl,
    _i2.ProgressCallback? onReceiveProgress,
    _i2.ProgressCallback? onSendProgress,
    _i7.CancelToken? cancelToken,
    Map<String, dynamic>? extra,
    Map<String, dynamic>? headers,
    bool? preserveHeaderCase,
    _i2.ResponseType? responseType,
    String? contentType,
    _i2.ValidateStatus? validateStatus,
    bool? receiveDataWhenStatusError,
    bool? followRedirects,
    int? maxRedirects,
    bool? persistentConnection,
    _i2.RequestEncoder? requestEncoder,
    _i2.ResponseDecoder? responseDecoder,
    _i2.ListFormat? listFormat,
    bool? setRequestContentTypeWhenNoPayload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #method: method,
              #sendTimeout: sendTimeout,
              #receiveTimeout: receiveTimeout,
              #connectTimeout: connectTimeout,
              #data: data,
              #path: path,
              #queryParameters: queryParameters,
              #baseUrl: baseUrl,
              #onReceiveProgress: onReceiveProgress,
              #onSendProgress: onSendProgress,
              #cancelToken: cancelToken,
              #extra: extra,
              #headers: headers,
              #preserveHeaderCase: preserveHeaderCase,
              #responseType: responseType,
              #contentType: contentType,
              #validateStatus: validateStatus,
              #receiveDataWhenStatusError: receiveDataWhenStatusError,
              #followRedirects: followRedirects,
              #maxRedirects: maxRedirects,
              #persistentConnection: persistentConnection,
              #requestEncoder: requestEncoder,
              #responseDecoder: responseDecoder,
              #listFormat: listFormat,
              #setRequestContentTypeWhenNoPayload:
                  setRequestContentTypeWhenNoPayload,
            }),
            returnValue: _FakeRequestOptions_1(
              this,
              Invocation.method(#copyWith, [], {
                #method: method,
                #sendTimeout: sendTimeout,
                #receiveTimeout: receiveTimeout,
                #connectTimeout: connectTimeout,
                #data: data,
                #path: path,
                #queryParameters: queryParameters,
                #baseUrl: baseUrl,
                #onReceiveProgress: onReceiveProgress,
                #onSendProgress: onSendProgress,
                #cancelToken: cancelToken,
                #extra: extra,
                #headers: headers,
                #preserveHeaderCase: preserveHeaderCase,
                #responseType: responseType,
                #contentType: contentType,
                #validateStatus: validateStatus,
                #receiveDataWhenStatusError: receiveDataWhenStatusError,
                #followRedirects: followRedirects,
                #maxRedirects: maxRedirects,
                #persistentConnection: persistentConnection,
                #requestEncoder: requestEncoder,
                #responseDecoder: responseDecoder,
                #listFormat: listFormat,
                #setRequestContentTypeWhenNoPayload:
                    setRequestContentTypeWhenNoPayload,
              }),
            ),
            returnValueForMissingStub: _FakeRequestOptions_1(
              this,
              Invocation.method(#copyWith, [], {
                #method: method,
                #sendTimeout: sendTimeout,
                #receiveTimeout: receiveTimeout,
                #connectTimeout: connectTimeout,
                #data: data,
                #path: path,
                #queryParameters: queryParameters,
                #baseUrl: baseUrl,
                #onReceiveProgress: onReceiveProgress,
                #onSendProgress: onSendProgress,
                #cancelToken: cancelToken,
                #extra: extra,
                #headers: headers,
                #preserveHeaderCase: preserveHeaderCase,
                #responseType: responseType,
                #contentType: contentType,
                #validateStatus: validateStatus,
                #receiveDataWhenStatusError: receiveDataWhenStatusError,
                #followRedirects: followRedirects,
                #maxRedirects: maxRedirects,
                #persistentConnection: persistentConnection,
                #requestEncoder: requestEncoder,
                #responseDecoder: responseDecoder,
                #listFormat: listFormat,
                #setRequestContentTypeWhenNoPayload:
                    setRequestContentTypeWhenNoPayload,
              }),
            ),
          )
          as _i2.RequestOptions);
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse<T> extends _i1.Mock implements _i8.Response<T> {
  @override
  _i2.RequestOptions get requestOptions =>
      (super.noSuchMethod(
            Invocation.getter(#requestOptions),
            returnValue: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
            returnValueForMissingStub: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
          )
          as _i2.RequestOptions);

  @override
  _i3.Headers get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: _FakeHeaders_2(this, Invocation.getter(#headers)),
            returnValueForMissingStub: _FakeHeaders_2(
              this,
              Invocation.getter(#headers),
            ),
          )
          as _i3.Headers);

  @override
  bool get isRedirect =>
      (super.noSuchMethod(
            Invocation.getter(#isRedirect),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i9.RedirectRecord> get redirects =>
      (super.noSuchMethod(
            Invocation.getter(#redirects),
            returnValue: <_i9.RedirectRecord>[],
            returnValueForMissingStub: <_i9.RedirectRecord>[],
          )
          as List<_i9.RedirectRecord>);

  @override
  Uri get realUri =>
      (super.noSuchMethod(
            Invocation.getter(#realUri),
            returnValue: _FakeUri_0(this, Invocation.getter(#realUri)),
            returnValueForMissingStub: _FakeUri_0(
              this,
              Invocation.getter(#realUri),
            ),
          )
          as Uri);

  @override
  Map<String, dynamic> get extra =>
      (super.noSuchMethod(
            Invocation.getter(#extra),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  set data(T? value) => super.noSuchMethod(
    Invocation.setter(#data, value),
    returnValueForMissingStub: null,
  );

  @override
  set requestOptions(_i2.RequestOptions? value) => super.noSuchMethod(
    Invocation.setter(#requestOptions, value),
    returnValueForMissingStub: null,
  );

  @override
  set statusCode(int? value) => super.noSuchMethod(
    Invocation.setter(#statusCode, value),
    returnValueForMissingStub: null,
  );

  @override
  set statusMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#statusMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(_i3.Headers? value) => super.noSuchMethod(
    Invocation.setter(#headers, value),
    returnValueForMissingStub: null,
  );

  @override
  set isRedirect(bool? value) => super.noSuchMethod(
    Invocation.setter(#isRedirect, value),
    returnValueForMissingStub: null,
  );

  @override
  set redirects(List<_i9.RedirectRecord>? value) => super.noSuchMethod(
    Invocation.setter(#redirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set extra(Map<String, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#extra, value),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DioException].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioException extends _i1.Mock implements _i4.DioException {
  @override
  _i2.RequestOptions get requestOptions =>
      (super.noSuchMethod(
            Invocation.getter(#requestOptions),
            returnValue: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
            returnValueForMissingStub: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
          )
          as _i2.RequestOptions);

  @override
  _i4.DioExceptionType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i4.DioExceptionType.connectionTimeout,
            returnValueForMissingStub: _i4.DioExceptionType.connectionTimeout,
          )
          as _i4.DioExceptionType);

  @override
  StackTrace get stackTrace =>
      (super.noSuchMethod(
            Invocation.getter(#stackTrace),
            returnValue: _FakeStackTrace_3(
              this,
              Invocation.getter(#stackTrace),
            ),
            returnValueForMissingStub: _FakeStackTrace_3(
              this,
              Invocation.getter(#stackTrace),
            ),
          )
          as StackTrace);

  @override
  set stringBuilder(_i4.DioExceptionReadableStringBuilder? value) =>
      super.noSuchMethod(
        Invocation.setter(#stringBuilder, value),
        returnValueForMissingStub: null,
      );

  @override
  _i4.DioException copyWith({
    _i2.RequestOptions? requestOptions,
    _i8.Response<dynamic>? response,
    _i4.DioExceptionType? type,
    Object? error,
    StackTrace? stackTrace,
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #requestOptions: requestOptions,
              #response: response,
              #type: type,
              #error: error,
              #stackTrace: stackTrace,
              #message: message,
            }),
            returnValue: _FakeDioException_4(
              this,
              Invocation.method(#copyWith, [], {
                #requestOptions: requestOptions,
                #response: response,
                #type: type,
                #error: error,
                #stackTrace: stackTrace,
                #message: message,
              }),
            ),
            returnValueForMissingStub: _FakeDioException_4(
              this,
              Invocation.method(#copyWith, [], {
                #requestOptions: requestOptions,
                #response: response,
                #type: type,
                #error: error,
                #stackTrace: stackTrace,
                #message: message,
              }),
            ),
          )
          as _i4.DioException);
}

/// A class which mocks [RequestInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestInterceptorHandler extends _i1.Mock
    implements _i5.RequestInterceptorHandler {
  @override
  _i10.Future<_i5.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i10.Future<_i5.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_5<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.InterceptorState<dynamic>>.value(
                  _FakeInterceptorState_5<dynamic>(
                    this,
                    Invocation.getter(#future),
                  ),
                ),
          )
          as _i10.Future<_i5.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isCompleted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void next(_i2.RequestOptions? requestOptions) => super.noSuchMethod(
    Invocation.method(#next, [requestOptions]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(
    _i8.Response<dynamic>? response, [
    bool? callFollowingResponseInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#resolve, [response, callFollowingResponseInterceptor]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(
    _i4.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ResponseInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseInterceptorHandler extends _i1.Mock
    implements _i5.ResponseInterceptorHandler {
  @override
  _i10.Future<_i5.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i10.Future<_i5.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_5<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.InterceptorState<dynamic>>.value(
                  _FakeInterceptorState_5<dynamic>(
                    this,
                    Invocation.getter(#future),
                  ),
                ),
          )
          as _i10.Future<_i5.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isCompleted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void next(_i8.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#next, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i8.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(
    _i4.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ErrorInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorInterceptorHandler extends _i1.Mock
    implements _i5.ErrorInterceptorHandler {
  @override
  _i10.Future<_i5.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i10.Future<_i5.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_5<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i5.InterceptorState<dynamic>>.value(
                  _FakeInterceptorState_5<dynamic>(
                    this,
                    Invocation.getter(#future),
                  ),
                ),
          )
          as _i10.Future<_i5.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isCompleted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void next(_i4.DioException? error) => super.noSuchMethod(
    Invocation.method(#next, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i8.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(_i4.DioException? error) => super.noSuchMethod(
    Invocation.method(#reject, [error]),
    returnValueForMissingStub: null,
  );
}
