// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/00_unit/server_domain_additional_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i13;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:shared_preferences/shared_preferences.dart' as _i12;
import 'package:silo_tavern/domain/connection/domain.dart' as _i7;
import 'package:silo_tavern/domain/connection/models.dart' as _i2;
import 'package:silo_tavern/domain/repositories.dart' as _i4;
import 'package:silo_tavern/domain/result.dart' as _i9;
import 'package:silo_tavern/domain/servers/models.dart' as _i6;
import 'package:silo_tavern/services/connection/models/models.dart' as _i10;
import 'package:silo_tavern/services/connection/network.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionSessionFactory_0 extends _i1.SmartFake
    implements _i2.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_1 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_2 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_3 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_4 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_5 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_6 extends _i1.SmartFake implements _i3.AppleOptions {
  _FakeAppleOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerStorage extends _i1.Mock implements _i4.ServerStorage {
  @override
  _i5.Future<List<_i6.Server>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i6.Server>>.value(<_i6.Server>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Server>>.value(
              <_i6.Server>[],
            ),
          )
          as _i5.Future<List<_i6.Server>>);

  @override
  _i5.Future<_i6.Server?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i6.Server?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Server?>.value(),
          )
          as _i5.Future<_i6.Server?>);

  @override
  _i5.Future<void> create(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#create, [server]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#update, [server]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [serverId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i7.ConnectionDomain {
  @override
  _i2.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i2.ConnectionSessionFactory);

  @override
  _i8.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i8.ConnectionSessionInterface?);

  @override
  _i5.Future<_i9.Result<void>> authenticateWithServer(
    _i6.Server? server,
    _i10.ConnectionCredentials? credentials, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authenticateWithServer,
              [server, credentials],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i5.Future<_i9.Result<void>>.value(
              _i11.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i9.Result<void>>.value(
              _i11.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i5.Future<_i9.Result<void>>);

  @override
  _i5.Future<_i9.Result<void>> obtainCsrfTokenForServer(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i5.Future<_i9.Result<void>>.value(
              _i11.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i9.Result<void>>.value(
              _i11.dummyValue<_i9.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i5.Future<_i9.Result<void>>);

  @override
  _i5.Future<_i9.Result<bool>> checkServerAvailability(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i5.Future<_i9.Result<bool>>.value(
              _i11.dummyValue<_i9.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i9.Result<bool>>.value(
              _i11.dummyValue<_i9.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
          )
          as _i5.Future<_i9.Result<bool>>);

  @override
  bool hasExistingSession(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasExistingSession, [server]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<bool> hasPersistentSession(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasPersistentSession, [server]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void testOnlyAddSession(
    String? serverId,
    _i8.ConnectionSessionInterface? session,
  ) => super.noSuchMethod(
    Invocation.method(#testOnlyAddSession, [serverId, session]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferencesAsync].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockSharedPreferencesAsync extends _i1.Mock
    implements _i12.SharedPreferencesAsync {
  @override
  _i5.Future<Set<String>> getKeys({Set<String>? allowList}) =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, [], {#allowList: allowList}),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i5.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<Map<String, Object?>> getAll({Set<String>? allowList}) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {#allowList: allowList}),
            returnValue: _i5.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, Object?>>.value(
              <String, Object?>{},
            ),
          )
          as _i5.Future<Map<String, Object?>>);

  @override
  _i5.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i5.Future<bool?>.value(),
            returnValueForMissingStub: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<int?> getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValue: _i5.Future<int?>.value(),
            returnValueForMissingStub: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<double?> getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: _i5.Future<double?>.value(),
            returnValueForMissingStub: _i5.Future<double?>.value(),
          )
          as _i5.Future<double?>);

  @override
  _i5.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<List<String>?> getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValue: _i5.Future<List<String>?>.value(),
            returnValueForMissingStub: _i5.Future<List<String>?>.value(),
          )
          as _i5.Future<List<String>?>);

  @override
  _i5.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clear({Set<String>? allowList}) =>
      (super.noSuchMethod(
            Invocation.method(#clear, [], {#allowList: allowList}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  @override
  _i3.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_1(this, Invocation.getter(#iOptions)),
            returnValueForMissingStub: _FakeIOSOptions_1(
              this,
              Invocation.getter(#iOptions),
            ),
          )
          as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_2(
              this,
              Invocation.getter(#aOptions),
            ),
            returnValueForMissingStub: _FakeAndroidOptions_2(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_3(
              this,
              Invocation.getter(#lOptions),
            ),
            returnValueForMissingStub: _FakeLinuxOptions_3(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_4(
              this,
              Invocation.getter(#wOptions),
            ),
            returnValueForMissingStub: _FakeWindowsOptions_4(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_5(
              this,
              Invocation.getter(#webOptions),
            ),
            returnValueForMissingStub: _FakeWebOptions_5(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i3.WebOptions);

  @override
  _i3.AppleOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeAppleOptions_6(
              this,
              Invocation.getter(#mOptions),
            ),
            returnValueForMissingStub: _FakeAppleOptions_6(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i3.AppleOptions);

  @override
  Map<String, List<_i13.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
            Invocation.getter(#getListeners),
            returnValue: <String, List<_i13.ValueChanged<String?>>>{},
            returnValueForMissingStub:
                <String, List<_i13.ValueChanged<String?>>>{},
          )
          as Map<String, List<_i13.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> write({
    required String? key,
    required String? value,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> read({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> containsKey({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> delete({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> readAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> deleteAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i5.Future<bool?>.value(),
            returnValueForMissingStub: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);
}
