// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/00_unit/server_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:silo_tavern/domain/connection/domain.dart' as _i7;
import 'package:silo_tavern/domain/connection/models.dart' as _i2;
import 'package:silo_tavern/domain/servers/models.dart' as _i6;
import 'package:silo_tavern/services/connection/models/models.dart' as _i9;
import 'package:silo_tavern/services/connection/network.dart' as _i8;
import 'package:silo_tavern/services/connection/storage.dart' as _i3;
import 'package:silo_tavern/services/servers/storage.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionSessionFactory_0 extends _i1.SmartFake
    implements _i2.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionStorage_1 extends _i1.SmartFake
    implements _i3.ConnectionStorage {
  _FakeConnectionStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionResult_2 extends _i1.SmartFake
    implements _i2.ConnectionResult {
  _FakeConnectionResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerStorage extends _i1.Mock implements _i4.ServerStorage {
  @override
  _i5.Future<List<_i6.Server>> listServers() =>
      (super.noSuchMethod(
            Invocation.method(#listServers, []),
            returnValue: _i5.Future<List<_i6.Server>>.value(<_i6.Server>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Server>>.value(
              <_i6.Server>[],
            ),
          )
          as _i5.Future<List<_i6.Server>>);

  @override
  _i5.Future<_i6.Server?> getServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getServer, [id]),
            returnValue: _i5.Future<_i6.Server?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Server?>.value(),
          )
          as _i5.Future<_i6.Server?>);

  @override
  _i5.Future<void> createServer(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#createServer, [server]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateServer(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [server]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteServer(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteServer, [serverId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i7.ConnectionDomain {
  @override
  _i2.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i2.ConnectionSessionFactory);

  @override
  _i3.ConnectionStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeConnectionStorage_1(
              this,
              Invocation.getter(#secureStorage),
            ),
            returnValueForMissingStub: _FakeConnectionStorage_1(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i3.ConnectionStorage);

  @override
  _i8.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i8.ConnectionSessionInterface?);

  @override
  _i5.Future<_i2.ConnectionResult> authenticateWithServer(
    _i6.Server? server,
    _i9.ConnectionCredentials? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithServer, [server, credentials]),
            returnValue: _i5.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_2(
                this,
                Invocation.method(#authenticateWithServer, [
                  server,
                  credentials,
                ]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_2(
                this,
                Invocation.method(#authenticateWithServer, [
                  server,
                  credentials,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.ConnectionResult>);

  @override
  _i5.Future<_i2.ConnectionResult> obtainCsrfTokenForServer(
    _i6.Server? server,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i5.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_2(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_2(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i5.Future<_i2.ConnectionResult>);

  @override
  _i5.Future<bool> checkServerAvailability(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool hasExistingSession(_i6.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasExistingSession, [server]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void testOnlyAddSession(
    String? serverId,
    _i8.ConnectionSessionInterface? session,
  ) => super.noSuchMethod(
    Invocation.method(#testOnlyAddSession, [serverId, session]),
    returnValueForMissingStub: null,
  );
}
