// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter/widgets.dart' as _i4;
import 'package:go_router/src/configuration.dart' as _i3;
import 'package:go_router/src/delegate.dart' as _i5;
import 'package:go_router/src/information_provider.dart' as _i6;
import 'package:go_router/src/match.dart' as _i12;
import 'package:go_router/src/parser.dart' as _i7;
import 'package:go_router/src/router.dart' as _i10;
import 'package:go_router/src/state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:silo_tavern/common/result.dart' as _i16;
import 'package:silo_tavern/domain/connection/domain.dart' as _i8;
import 'package:silo_tavern/domain/connection/models.dart' as _i9;
import 'package:silo_tavern/domain/servers/domain.dart' as _i14;
import 'package:silo_tavern/domain/servers/models.dart' as _i15;
import 'package:silo_tavern/services/connection/models/models.dart' as _i18;
import 'package:silo_tavern/services/connection/network.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoRouterState_0 extends _i1.SmartFake implements _i2.GoRouterState {
  _FakeGoRouterState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteConfiguration_1 extends _i1.SmartFake
    implements _i3.RouteConfiguration {
  _FakeRouteConfiguration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackButtonDispatcher_2 extends _i1.SmartFake
    implements _i4.BackButtonDispatcher {
  _FakeBackButtonDispatcher_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouterDelegate_3 extends _i1.SmartFake
    implements _i5.GoRouterDelegate {
  _FakeGoRouterDelegate_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationProvider_4 extends _i1.SmartFake
    implements _i6.GoRouteInformationProvider {
  _FakeGoRouteInformationProvider_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoRouteInformationParser_5 extends _i1.SmartFake
    implements _i7.GoRouteInformationParser {
  _FakeGoRouteInformationParser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionDomain_6 extends _i1.SmartFake
    implements _i8.ConnectionDomain {
  _FakeConnectionDomain_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionSessionFactory_7 extends _i1.SmartFake
    implements _i9.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouter extends _i1.Mock implements _i10.GoRouter {
  @override
  _i2.GoRouterState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGoRouterState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeGoRouterState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.GoRouterState);

  @override
  _i3.RouteConfiguration get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
            returnValueForMissingStub: _FakeRouteConfiguration_1(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i3.RouteConfiguration);

  @override
  _i4.BackButtonDispatcher get backButtonDispatcher =>
      (super.noSuchMethod(
            Invocation.getter(#backButtonDispatcher),
            returnValue: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
            returnValueForMissingStub: _FakeBackButtonDispatcher_2(
              this,
              Invocation.getter(#backButtonDispatcher),
            ),
          )
          as _i4.BackButtonDispatcher);

  @override
  _i5.GoRouterDelegate get routerDelegate =>
      (super.noSuchMethod(
            Invocation.getter(#routerDelegate),
            returnValue: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
            returnValueForMissingStub: _FakeGoRouterDelegate_3(
              this,
              Invocation.getter(#routerDelegate),
            ),
          )
          as _i5.GoRouterDelegate);

  @override
  _i6.GoRouteInformationProvider get routeInformationProvider =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationProvider),
            returnValue: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationProvider_4(
              this,
              Invocation.getter(#routeInformationProvider),
            ),
          )
          as _i6.GoRouteInformationProvider);

  @override
  _i7.GoRouteInformationParser get routeInformationParser =>
      (super.noSuchMethod(
            Invocation.getter(#routeInformationParser),
            returnValue: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
            returnValueForMissingStub: _FakeGoRouteInformationParser_5(
              this,
              Invocation.getter(#routeInformationParser),
            ),
          )
          as _i7.GoRouteInformationParser);

  @override
  bool get overridePlatformDefaultLocation =>
      (super.noSuchMethod(
            Invocation.getter(#overridePlatformDefaultLocation),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set configuration(_i3.RouteConfiguration? value) => super.noSuchMethod(
    Invocation.setter(#configuration, value),
    returnValueForMissingStub: null,
  );

  @override
  set routerDelegate(_i5.GoRouterDelegate? value) => super.noSuchMethod(
    Invocation.setter(#routerDelegate, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeInformationProvider(_i6.GoRouteInformationProvider? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationProvider, value),
        returnValueForMissingStub: null,
      );

  @override
  set routeInformationParser(_i7.GoRouteInformationParser? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeInformationParser, value),
        returnValueForMissingStub: null,
      );

  @override
  bool canPop() =>
      (super.noSuchMethod(
            Invocation.method(#canPop, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String namedLocation(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedLocation,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #fragment: fragment,
              },
            ),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(
                #namedLocation,
                [name],
                {
                  #pathParameters: pathParameters,
                  #queryParameters: queryParameters,
                  #fragment: fragment,
                },
              ),
            ),
          )
          as String);

  @override
  void go(String? location, {Object? extra}) => super.noSuchMethod(
    Invocation.method(#go, [location], {#extra: extra}),
    returnValueForMissingStub: null,
  );

  @override
  void restore(_i12.RouteMatchList? matchList) => super.noSuchMethod(
    Invocation.method(#restore, [matchList]),
    returnValueForMissingStub: null,
  );

  @override
  void goNamed(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
    String? fragment,
  }) => super.noSuchMethod(
    Invocation.method(
      #goNamed,
      [name],
      {
        #pathParameters: pathParameters,
        #queryParameters: queryParameters,
        #extra: extra,
        #fragment: fragment,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<T?> push<T extends Object?>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#push, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacement<T extends Object?>(
    String? location, {
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushReplacement, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> pushReplacementNamed<T extends Object?>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pushReplacementNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replace<T>(String? location, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [location], {#extra: extra}),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  _i13.Future<T?> replaceNamed<T>(
    String? name, {
    Map<String, String>? pathParameters = const {},
    Map<String, dynamic>? queryParameters = const {},
    Object? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceNamed,
              [name],
              {
                #pathParameters: pathParameters,
                #queryParameters: queryParameters,
                #extra: extra,
              },
            ),
            returnValue: _i13.Future<T?>.value(),
            returnValueForMissingStub: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ServerDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerDomain extends _i1.Mock implements _i14.ServerDomain {
  @override
  _i8.ConnectionDomain get connectionDomain =>
      (super.noSuchMethod(
            Invocation.getter(#connectionDomain),
            returnValue: _FakeConnectionDomain_6(
              this,
              Invocation.getter(#connectionDomain),
            ),
            returnValueForMissingStub: _FakeConnectionDomain_6(
              this,
              Invocation.getter(#connectionDomain),
            ),
          )
          as _i8.ConnectionDomain);

  @override
  List<_i15.Server> get servers =>
      (super.noSuchMethod(
            Invocation.getter(#servers),
            returnValue: <_i15.Server>[],
            returnValueForMissingStub: <_i15.Server>[],
          )
          as List<_i15.Server>);

  @override
  int get serverCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i13.Future<_i16.Result<void>> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#initialize, []),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#initialize, []),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i13.Future<_i16.Result<void>> addServer(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#addServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#addServer, [server]),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i13.Future<_i16.Result<void>> updateServer(_i15.Server? updatedServer) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [updatedServer]),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#updateServer, [updatedServer]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#updateServer, [updatedServer]),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i13.Future<_i16.Result<void>> removeServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [id]),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#removeServer, [id]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#removeServer, [id]),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i15.Server? findServerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findServerById, [id]),
            returnValueForMissingStub: null,
          )
          as _i15.Server?);

  @override
  void updateServerStatus(String? serverId, _i15.ServerStatus? status) =>
      super.noSuchMethod(
        Invocation.method(#updateServerStatus, [serverId, status]),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> checkAllServerStatuses(
    void Function(_i15.Server)? serverUpdateCallback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAllServerStatuses, [serverUpdateCallback]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i8.ConnectionDomain {
  @override
  _i9.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_7(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_7(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i9.ConnectionSessionFactory);

  @override
  _i17.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i17.ConnectionSessionInterface?);

  @override
  _i13.Future<_i16.Result<void>> authenticateWithServer(
    _i15.Server? server,
    _i18.ConnectionCredentials? credentials, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authenticateWithServer,
              [server, credentials],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i13.Future<_i16.Result<void>> obtainCsrfTokenForServer(
    _i15.Server? server,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<void>>.value(
              _i11.dummyValue<_i16.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i13.Future<_i16.Result<void>>);

  @override
  _i13.Future<_i16.Result<bool>> checkServerAvailability(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i13.Future<_i16.Result<bool>>.value(
              _i11.dummyValue<_i16.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i16.Result<bool>>.value(
              _i11.dummyValue<_i16.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
          )
          as _i13.Future<_i16.Result<bool>>);

  @override
  bool hasExistingSession(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasExistingSession, [server]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.Future<bool> hasPersistentSession(_i15.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasPersistentSession, [server]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  void testOnlyAddSession(
    String? serverId,
    _i17.ConnectionSessionInterface? session,
  ) => super.noSuchMethod(
    Invocation.method(#testOnlyAddSession, [serverId, session]),
    returnValueForMissingStub: null,
  );
}
