// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:silo_tavern/domain/connection/domain.dart' as _i2;
import 'package:silo_tavern/domain/connection/models.dart' as _i4;
import 'package:silo_tavern/domain/servers/domain.dart' as _i6;
import 'package:silo_tavern/domain/servers/models.dart' as _i3;
import 'package:silo_tavern/services/connection/models/models.dart' as _i9;
import 'package:silo_tavern/services/connection/network.dart' as _i8;
import 'package:silo_tavern/services/connection/storage.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionDomain_0 extends _i1.SmartFake
    implements _i2.ConnectionDomain {
  _FakeConnectionDomain_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServerConnectionResult_1 extends _i1.SmartFake
    implements _i3.ServerConnectionResult {
  _FakeServerConnectionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionSessionFactory_2 extends _i1.SmartFake
    implements _i4.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionStorage_3 extends _i1.SmartFake
    implements _i5.ConnectionStorage {
  _FakeConnectionStorage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionResult_4 extends _i1.SmartFake
    implements _i4.ConnectionResult {
  _FakeConnectionResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerDomain extends _i1.Mock implements _i6.ServerDomain {
  @override
  _i2.ConnectionDomain get connectionDomain =>
      (super.noSuchMethod(
            Invocation.getter(#connectionDomain),
            returnValue: _FakeConnectionDomain_0(
              this,
              Invocation.getter(#connectionDomain),
            ),
            returnValueForMissingStub: _FakeConnectionDomain_0(
              this,
              Invocation.getter(#connectionDomain),
            ),
          )
          as _i2.ConnectionDomain);

  @override
  List<_i3.Server> get servers =>
      (super.noSuchMethod(
            Invocation.getter(#servers),
            returnValue: <_i3.Server>[],
            returnValueForMissingStub: <_i3.Server>[],
          )
          as List<_i3.Server>);

  @override
  int get serverCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addServer(_i3.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateServer(_i3.Server? updatedServer) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [updatedServer]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i3.Server? findServerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findServerById, [id]),
            returnValueForMissingStub: null,
          )
          as _i3.Server?);

  @override
  void updateServerStatus(String? serverId, _i3.ServerStatus? status) =>
      super.noSuchMethod(
        Invocation.method(#updateServerStatus, [serverId, status]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.ServerConnectionResult> connectToServer(_i3.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#connectToServer, [server]),
            returnValue: _i7.Future<_i3.ServerConnectionResult>.value(
              _FakeServerConnectionResult_1(
                this,
                Invocation.method(#connectToServer, [server]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i3.ServerConnectionResult>.value(
                  _FakeServerConnectionResult_1(
                    this,
                    Invocation.method(#connectToServer, [server]),
                  ),
                ),
          )
          as _i7.Future<_i3.ServerConnectionResult>);

  @override
  _i7.Future<void> checkAllServerStatuses(
    void Function(_i3.Server)? serverUpdateCallback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAllServerStatuses, [serverUpdateCallback]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i2.ConnectionDomain {
  @override
  _i4.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_2(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_2(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i4.ConnectionSessionFactory);

  @override
  _i5.ConnectionStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeConnectionStorage_3(
              this,
              Invocation.getter(#secureStorage),
            ),
            returnValueForMissingStub: _FakeConnectionStorage_3(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i5.ConnectionStorage);

  @override
  _i7.Future<_i4.ConnectionResult> connectToServer(_i3.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#connectToServer, [server]),
            returnValue: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#connectToServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#connectToServer, [server]),
              ),
            ),
          )
          as _i7.Future<_i4.ConnectionResult>);

  @override
  _i8.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i8.ConnectionSessionInterface?);

  @override
  _i7.Future<_i4.ConnectionResult> authenticateWithServer(
    _i3.Server? server,
    _i9.ConnectionCredentials? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithServer, [server, credentials]),
            returnValue: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#authenticateWithServer, [
                  server,
                  credentials,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#authenticateWithServer, [
                  server,
                  credentials,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.ConnectionResult>);

  @override
  _i7.Future<_i4.ConnectionResult> obtainCsrfTokenForServer(
    _i3.Server? server,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.ConnectionResult>.value(
              _FakeConnectionResult_4(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i7.Future<_i4.ConnectionResult>);

  @override
  _i7.Future<bool> checkServerAvailability(_i3.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
