// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:silo_tavern/common/result.dart' as _i7;
import 'package:silo_tavern/domain/connection/domain.dart' as _i2;
import 'package:silo_tavern/domain/connection/models.dart' as _i3;
import 'package:silo_tavern/domain/servers/domain.dart' as _i4;
import 'package:silo_tavern/domain/servers/models.dart' as _i5;
import 'package:silo_tavern/services/connection/models/models.dart' as _i10;
import 'package:silo_tavern/services/connection/network.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionDomain_0 extends _i1.SmartFake
    implements _i2.ConnectionDomain {
  _FakeConnectionDomain_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnectionSessionFactory_1 extends _i1.SmartFake
    implements _i3.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerDomain extends _i1.Mock implements _i4.ServerDomain {
  @override
  _i2.ConnectionDomain get connectionDomain =>
      (super.noSuchMethod(
            Invocation.getter(#connectionDomain),
            returnValue: _FakeConnectionDomain_0(
              this,
              Invocation.getter(#connectionDomain),
            ),
            returnValueForMissingStub: _FakeConnectionDomain_0(
              this,
              Invocation.getter(#connectionDomain),
            ),
          )
          as _i2.ConnectionDomain);

  @override
  List<_i5.Server> get servers =>
      (super.noSuchMethod(
            Invocation.getter(#servers),
            returnValue: <_i5.Server>[],
            returnValueForMissingStub: <_i5.Server>[],
          )
          as List<_i5.Server>);

  @override
  int get serverCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i6.Future<_i7.Result<void>> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#initialize, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#initialize, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> addServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#addServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#addServer, [server]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> updateServer(_i5.Server? updatedServer) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [updatedServer]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateServer, [updatedServer]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateServer, [updatedServer]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> removeServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [id]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#removeServer, [id]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#removeServer, [id]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i5.Server? findServerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findServerById, [id]),
            returnValueForMissingStub: null,
          )
          as _i5.Server?);

  @override
  void updateServerStatus(String? serverId, _i5.ServerStatus? status) =>
      super.noSuchMethod(
        Invocation.method(#updateServerStatus, [serverId, status]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> checkAllServerStatuses(
    void Function(_i5.Server)? serverUpdateCallback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAllServerStatuses, [serverUpdateCallback]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i2.ConnectionDomain {
  @override
  _i3.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_1(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_1(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i3.ConnectionSessionFactory);

  @override
  _i9.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i9.ConnectionSessionInterface?);

  @override
  _i6.Future<_i7.Result<void>> authenticateWithServer(
    _i5.Server? server,
    _i10.ConnectionCredentials? credentials, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authenticateWithServer,
              [server, credentials],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> obtainCsrfTokenForServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<bool>> checkServerAvailability(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<bool>>);

  @override
  bool hasExistingSession(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasExistingSession, [server]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<bool> hasPersistentSession(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasPersistentSession, [server]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void testOnlyAddSession(
    String? serverId,
    _i9.ConnectionSessionInterface? session,
  ) => super.noSuchMethod(
    Invocation.method(#testOnlyAddSession, [serverId, session]),
    returnValueForMissingStub: null,
  );
}
