// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/server_list_connection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:silo_tavern/domain/connection/domain.dart' as _i6;
import 'package:silo_tavern/domain/connection/models.dart' as _i2;
import 'package:silo_tavern/domain/servers/models.dart' as _i5;
import 'package:silo_tavern/services/servers/storage.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionResult_0 extends _i1.SmartFake
    implements _i2.ConnectionResult {
  _FakeConnectionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticatedClient_1 extends _i1.SmartFake
    implements _i2.AuthenticatedClient {
  _FakeAuthenticatedClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerStorage extends _i1.Mock implements _i3.ServerStorage {
  @override
  _i4.Future<List<_i5.Server>> listServers() =>
      (super.noSuchMethod(
            Invocation.method(#listServers, []),
            returnValue: _i4.Future<List<_i5.Server>>.value(<_i5.Server>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Server>>.value(
              <_i5.Server>[],
            ),
          )
          as _i4.Future<List<_i5.Server>>);

  @override
  _i4.Future<_i5.Server?> getServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getServer, [id]),
            returnValue: _i4.Future<_i5.Server?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Server?>.value(),
          )
          as _i4.Future<_i5.Server?>);

  @override
  _i4.Future<void> createServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#createServer, [server]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [server]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteServer(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteServer, [serverId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i6.ConnectionDomain {
  @override
  _i4.Future<_i2.ConnectionResult> connectToServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#connectToServer, [server]),
            returnValue: _i4.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_0(
                this,
                Invocation.method(#connectToServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_0(
                this,
                Invocation.method(#connectToServer, [server]),
              ),
            ),
          )
          as _i4.Future<_i2.ConnectionResult>);

  @override
  _i4.Future<_i2.AuthenticatedClient> getAuthenticatedClient(
    String? serverId,
    String? baseUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticatedClient, [serverId, baseUrl]),
            returnValue: _i4.Future<_i2.AuthenticatedClient>.value(
              _FakeAuthenticatedClient_1(
                this,
                Invocation.method(#getAuthenticatedClient, [serverId, baseUrl]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.AuthenticatedClient>.value(
                  _FakeAuthenticatedClient_1(
                    this,
                    Invocation.method(#getAuthenticatedClient, [
                      serverId,
                      baseUrl,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.AuthenticatedClient>);

  @override
  _i4.Future<void> disconnect(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [serverId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ConnectionResult> reauthenticate(
    String? serverId,
    String? serverUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, [serverId, serverUrl]),
            returnValue: _i4.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_0(
                this,
                Invocation.method(#reauthenticate, [serverId, serverUrl]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ConnectionResult>.value(
              _FakeConnectionResult_0(
                this,
                Invocation.method(#reauthenticate, [serverId, serverUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.ConnectionResult>);

  @override
  _i4.Future<bool> isConnected(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, [serverId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
