// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/server_list_connection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:silo_tavern/domain/servers/models.dart' as _i4;
import 'package:silo_tavern/services/connection/service.dart' as _i5;
import 'package:silo_tavern/services/servers/storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ServerStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerStorage extends _i1.Mock implements _i2.ServerStorage {
  @override
  _i3.Future<List<_i4.Server>> listServers() =>
      (super.noSuchMethod(
            Invocation.method(#listServers, []),
            returnValue: _i3.Future<List<_i4.Server>>.value(<_i4.Server>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Server>>.value(
              <_i4.Server>[],
            ),
          )
          as _i3.Future<List<_i4.Server>>);

  @override
  _i3.Future<_i4.Server?> getServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getServer, [id]),
            returnValue: _i3.Future<_i4.Server?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Server?>.value(),
          )
          as _i3.Future<_i4.Server?>);

  @override
  _i3.Future<void> createServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#createServer, [server]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [server]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteServer(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteServer, [serverId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ServerConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerConnectionService extends _i1.Mock
    implements _i5.ServerConnectionService {
  @override
  _i3.Future<String> getCsrfToken(String? serverAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getCsrfToken, [serverAddress]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getCsrfToken, [serverAddress]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getCsrfToken, [serverAddress]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> authenticate(
    String? serverAddress,
    String? csrfToken,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [
              serverAddress,
              csrfToken,
              username,
              password,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeTokens(String? serverId, Map<String, String>? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#storeTokens, [serverId, tokens]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
