// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/01_widget/servers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mutex/mutex.dart' as _i2;
import 'package:silo_tavern/domain/server.dart' as _i4;
import 'package:silo_tavern/domain/server_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMutex_0 extends _i1.SmartFake implements _i2.Mutex {
  _FakeMutex_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerService extends _i1.Mock implements _i3.ServerService {
  @override
  _i2.Mutex get locker =>
      (super.noSuchMethod(
            Invocation.getter(#locker),
            returnValue: _FakeMutex_0(this, Invocation.getter(#locker)),
            returnValueForMissingStub: _FakeMutex_0(
              this,
              Invocation.getter(#locker),
            ),
          )
          as _i2.Mutex);

  @override
  List<_i4.Server> get servers =>
      (super.noSuchMethod(
            Invocation.getter(#servers),
            returnValue: <_i4.Server>[],
            returnValueForMissingStub: <_i4.Server>[],
          )
          as List<_i4.Server>);

  @override
  int get serverCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addServer(_i4.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#addServer, [server]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateServer(_i4.Server? updatedServer) =>
      (super.noSuchMethod(
            Invocation.method(#updateServer, [updatedServer]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeServer, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i4.Server? findServerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findServerById, [id]),
            returnValueForMissingStub: null,
          )
          as _i4.Server?);
}
