// Mocks generated by Mockito 5.4.6 from annotations
// in silo_tavern/test/02_integration/auth_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:silo_tavern/domain/connection/domain.dart' as _i6;
import 'package:silo_tavern/domain/connection/models.dart' as _i2;
import 'package:silo_tavern/domain/result.dart' as _i8;
import 'package:silo_tavern/domain/servers/models.dart' as _i5;
import 'package:silo_tavern/domain/servers/repository.dart' as _i3;
import 'package:silo_tavern/services/connection/models/models.dart' as _i9;
import 'package:silo_tavern/services/connection/network.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConnectionSessionFactory_0 extends _i1.SmartFake
    implements _i2.ConnectionSessionFactory {
  _FakeConnectionSessionFactory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerRepository extends _i1.Mock implements _i3.ServerRepository {
  @override
  _i4.Future<List<_i5.Server>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i5.Server>>.value(<_i5.Server>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.Server>>.value(
              <_i5.Server>[],
            ),
          )
          as _i4.Future<List<_i5.Server>>);

  @override
  _i4.Future<_i5.Server?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i5.Server?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Server?>.value(),
          )
          as _i4.Future<_i5.Server?>);

  @override
  _i4.Future<void> create(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#create, [server]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> update(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#update, [server]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ConnectionDomain].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionDomain extends _i1.Mock implements _i6.ConnectionDomain {
  @override
  _i2.ConnectionSessionFactory get sessionFactory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionFactory),
            returnValue: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
            returnValueForMissingStub: _FakeConnectionSessionFactory_0(
              this,
              Invocation.getter(#sessionFactory),
            ),
          )
          as _i2.ConnectionSessionFactory);

  @override
  _i7.ConnectionSessionInterface? getClient(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getClient, [serverId]),
            returnValueForMissingStub: null,
          )
          as _i7.ConnectionSessionInterface?);

  @override
  _i4.Future<_i8.Result<void>> authenticateWithServer(
    _i5.Server? server,
    _i9.ConnectionCredentials? credentials, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #authenticateWithServer,
              [server, credentials],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i4.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(
                  #authenticateWithServer,
                  [server, credentials],
                  {#rememberMe: rememberMe},
                ),
              ),
            ),
          )
          as _i4.Future<_i8.Result<void>>);

  @override
  _i4.Future<_i8.Result<void>> obtainCsrfTokenForServer(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#obtainCsrfTokenForServer, [server]),
            returnValue: _i4.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i8.Result<void>>.value(
              _i10.dummyValue<_i8.Result<void>>(
                this,
                Invocation.method(#obtainCsrfTokenForServer, [server]),
              ),
            ),
          )
          as _i4.Future<_i8.Result<void>>);

  @override
  _i4.Future<_i8.Result<bool>> checkServerAvailability(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#checkServerAvailability, [server]),
            returnValue: _i4.Future<_i8.Result<bool>>.value(
              _i10.dummyValue<_i8.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i8.Result<bool>>.value(
              _i10.dummyValue<_i8.Result<bool>>(
                this,
                Invocation.method(#checkServerAvailability, [server]),
              ),
            ),
          )
          as _i4.Future<_i8.Result<bool>>);

  @override
  bool hasExistingSession(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasExistingSession, [server]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<bool> hasPersistentSession(_i5.Server? server) =>
      (super.noSuchMethod(
            Invocation.method(#hasPersistentSession, [server]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void testOnlyAddSession(
    String? serverId,
    _i7.ConnectionSessionInterface? session,
  ) => super.noSuchMethod(
    Invocation.method(#testOnlyAddSession, [serverId, session]),
    returnValueForMissingStub: null,
  );
}
